//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HTK_DatabaseEntities : DbContext
    {
        public HTK_DatabaseEntities()
            : base("name=HTK_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Classification> Classifications { get; set; }
        public virtual DbSet<Pitch> Pitches { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
    }
}
